const projectsList = [
  {
    id: 1,
    title: "AI Dog Breed Classifier 🐕",
    description:
      "I developed a full-stack AI image classification application, from concept to serverless cloud deployment. My responsibilities included training a Deep Learning model with TensorFlow/Keras, building a RESTful API with FastAPI, and containerizing services with Docker. I architected and automated the CI/CD pipeline using GitHub Actions, deploying the solution onto AWS App Runner for cost-optimized serverless hosting with automatic scaling and pay-per-use pricing.",
    techStack: [
      "Python",
      "TensorFlow",
      "Next.js",
      "Docker",
      "AWS App Runner",
      "AWS ECR",
      "FastAPI",
      "GitHub Actions",
      "Keras",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
      "Zustand",
    ],
    category: "AI/ML & Cloud",
    status: "Completed" as const,
    featured: true,
    demoUrl: null,
    // demoUrl: "https://dog-classifier.gabriel-baptista.dev/",
    githubUrl: "https://github.com/gbcbaptista/ai-image-dogs-classifier",
    startDate: "June 2025",
    completionDate: undefined,
  },
  {
    id: 2,
    title: "Kaggle Competitions Journey",
    description:
      "A deep dive into ML fundamentals where I build, debug, and refine algorithms from scratch. In the Titanic challenge, I implemented Logistic Regression using only NumPy, engineered complex features, and troubleshot numerical stability issues by implementing a feature scaler, ultimately matching Scikit-learn's benchmark performance.",
    techStack: ["Python", "NumPy", "Pandas", "Matplotlib", "Scikit-learn"],
    category: "AI/ML",
    status: "Development" as const,
    featured: false,
    demoUrl: null,
    githubUrl: "https://github.com/gbcbaptista/kaggle-competitions",
    startDate: "May 2025",
    completionDate: undefined,
  },
  {
    id: 3,
    title: "Real-Time IoT Temperature Dashboard 🌡️",
    description:
      "Developed a complete, end-to-end IoT solution, from hardware to a globally deployed web application. This project captures real-time temperature data from an ESP32 microcontroller, securely ingests it via MQTT into a fully serverless AWS backend, and visualizes the data on a dynamic Next.js dashboard. The architecture is event-driven, featuring real-time updates via WebSockets and automated frontend deployments through a CI/CD pipeline with GitHub Actions.",
    techStack: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Zustand",
      "Chart.js",
      "AWS IoT Core",
      "AWS Lambda",
      "Amazon DynamoDB",
      "API Gateway (REST & WebSocket)",
      "Amazon S3",
      "Amazon CloudFront",
      "AWS IAM",
      "GitHub Actions",
      "ESP32",
      "MQTT",
    ],
    category: "IoT & Full-Stack Cloud",
    status: "Completed" as const,
    featured: true,
    demoUrl: "https://rt-temperature-monitor.gabriel-baptista.dev/",
    githubUrl: "https://github.com/gbcbaptista/temperature-monitor",
    startDate: "September 2025",
    completionDate: "September 2025",
  },
];

export default projectsList;
